# Generated by Django 3.1.7 on 2021-05-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('medicine_price', models.FloatField()),
                ('payment', models.FloatField(blank=True, default=0.0, null=True)),
                ('payment_at_a_time', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=16)),
                ('salary_amount', models.FloatField()),
                ('payment', models.CharField(default='', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalesManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_medicine', models.IntegerField(blank=True, default=0, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('sold_number_of_medicine', models.IntegerField(blank=True, default=0, null=True)),
                ('sold_at_a_time', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('expense', models.FloatField(default=0.0)),
                ('selling', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('medicine_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.salesmanagement')),
            ],
            options={
                'verbose_name_plural': 'Medicine Histories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.customer')),
            ],
            options={
                'verbose_name_plural': 'Customers Histories',
                'ordering': ('created_at',),
            },
        ),
    ]
