# Generated by Django 3.1.7 on 2021-05-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanagement',
            name='sold_number_of_medicine',
            field=models.IntegerField(default=0),
        ),
    ]
