# Generated by Django 3.1.7 on 2021-05-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_salesmanagement_sold_number_of_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanagement',
            name='sold_at_a_time',
            field=models.IntegerField(default=0),
        ),
    ]
