# Generated by Django 3.1.7 on 2021-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210518_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
