# Generated by Django 3.1.7 on 2021-05-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_salesmanagement_sold_at_a_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanagement',
            name='sold_number_of_medicine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
