# Generated by Django 3.1.7 on 2021-06-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210523_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
