# Generated by Django 3.1.7 on 2021-05-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210518_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklessmedicine',
            name='original_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stocklessmedicine',
            name='selling_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
