# Generated by Django 3.1.7 on 2021-05-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210518_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklessmedicine',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stocklessmedicine',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='stocklessmedicine',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
