# Generated by Django 3.1.7 on 2021-05-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210504_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanagement',
            name='sold_at_a_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
