# Generated by Django 3.1.7 on 2021-05-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210518_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklessmedicine',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='stocklessmedicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stocklessmedicine',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stocklessmedicine',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='stocklessmedicine',
            name='selling_price',
        ),
    ]
