# Generated by Django 3.1.7 on 2021-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210518_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
