# Generated by Django 3.1.7 on 2021-05-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210518_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='customer_name',
        ),
    ]
